# Generated by Django 5.0.4 on 2024-05-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seller_rename_available_product_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
