# Generated by Django 5.0.4 on 2024-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_is_available_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='available',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
