# Generated by Django 5.0.4 on 2024-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.CharField(default=18, max_length=2),
            preserve_default=False,
        ),
    ]
