# Generated by Django 5.0.4 on 2024-05-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_order_items_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.transaction'),
        ),
    ]
